name: Create Tag

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Choose semver level'
        required: true
        default: Patch
        type: choice
        options:
          - Major
          - Minor
          - Patch

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: write
      packages: write
    concurrency:
      group: ${{ github.repository }}-${{ github.ref_name }}
    timeout-minutes: 10
    steps:
      - name: Checkout new semver tag action
        uses: actions/checkout@v6
        with:
          repository: timewave-ab/action-new-semver-tag
          path: ./actions/new-semver-tag
          ref: main
          token: ${{ secrets.ACTIONS_PERSONAL_ACCESS_TOKEN }}

      - uses: ./actions/new-semver-tag
        id: new-tag
        with:
          gitCommitEmail: "utveckling@timewave.se"
          tagType: ${{ inputs.releaseType }}
          token: ${{ secrets.ACTIONS_PERSONAL_ACCESS_TOKEN }}

      - name: Use the output
        run: |
          echo "The new tag is ${{ steps.new-tag.outputs.newTag }}"
